name: Release
on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
      - run: npm ci
      - name: Build and release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run deploy
